# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: Node.js Package

on:
  push:
    branches: [master]

jobs:
  build-npm:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
      - uses: actions/checkout@v3
      - name: Download Node
      - uses: actions/setup-node@v3
        with:
          node-version: '16.13.2'
      - name: Install Dependencies
      - run: npm ci
      - name: Build
      - run: npm run build
      - name: Build Docs
      - run: npm run doc
      - name: Npm Publish
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
